name: Transpire Module CI

on:
  workflow_call:
    inputs:
      module-name:
        required: true
        type: string
    secrets:
      HARBOR_USERNAME:
        required: true
      HARBOR_PASSWORD:
        required: true

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    container: harbor.ocf.berkeley.edu/ocf/transpire/transpire:main
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ocf/kubernetes
      - id: set-matrix
        run: transpire image build ${{ inputs.module-name }} -o gha
    outputs:
      image_matrix: ${{ steps.set-matrix.outputs.image_matrix }}

  build-images:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJson(needs.build-matrix.outputs.image_matrix) }}
    steps:
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: harbor.ocf.berkeley.edu
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: harbor.ocf.berkeley.edu/ocf/${{ inputs.module-name }}/${{ matrix.image.name }}
          tags: |
            type=sha
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

      - uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.image.context }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
